# Generated by Django 4.2.5 on 2025-03-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default=1, upload_to='dishes'),
            preserve_default=False,
        ),
    ]
